### PR TITLE
#2: Writing some docs

### PR DESCRIPTION
**Pull request by lmorchard**
Adding a short usage section to README, along with a longer example.

### CODE REVIEW

**Comment by tofumatt** [comment]
Looks like it's not passing the code quality standards... Could you tweak the example file to fix those errors?
- tofumatt

**Comment by lmorchard** [comment]
Bah! Here's an amended commit that hopefully passes the gauntlet better

**Comment by tofumatt** [comment]
Thanks much :+1:

**Comment by sole** [comment]
The gauntlet MUST be passed

*The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in the normative parts of this document are to be interpreted as described in [RFC2119]

**Comment by tofumatt** [comment]
What?

**Comment by sole** [comment]
haha @tofumatt that's the usual blubber in spec texts :D - every time I hear "MUST" I think of that paragraph :)

**Comment by tofumatt** [comment]
Lol. I lacked the context.
- tofumatt

**Pull request merged**
